import type { Metadata } from "next";
import Header from "./components/Header";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import { FiltersProvider } from "./context/ContextFilters";
import { SearchProvider } from "./context/SearchContext";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "ZonaQuintas | El lugar para disfrutar tus fin de semeanas",
  description: "Generated by create next app",
  keywords: "ZonaQuintas, fin de semana, vacaciones, viajes, hotel, apartamento, alquiler, reservas",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="apple-touch-icon" href="/logo.png" />
      </head>
      <FiltersProvider>
      <SearchProvider>
        <body className={`bg-[#f7f3f0] mt-32 ${inter.className}`}>
          <Header />
          {children}
          <Footer />
        </body>
      </SearchProvider>
      </FiltersProvider>
    </html>
  );
}
